### ISSUE TITLE
Исправления и TODO (расширяемый ишус)

### ISSUE THREAD

**Issue by stigGGGer** [Demonmiker/VentWPF#118]
- [x] Расчет падения давления по ярусам (вытяжка и приток)
- [x] данные FanSelect
- [ ] простая схема установки
- [x] шрифт на предпросмотре отчета (сделать цифры строгим стилем)
